### ISSUE TITLE
more of a question : can't import app config via replicatedctl

### ISSUE THREAD

**Issue by pbenefice** [joestack/pTFE-auto-install#2]
Hello @joestack ,

It's more of a question than an issue but I'm struggling soo hard with this and thought you might have an answer... so I'm trying my luck 😇 

I can't find out how to load the application config with replicatedctl via ansible with the `app-config import`.

I have a json file and I try to inject it to stdin of **replicatedctl app-config import** as follow : 

```
- name: "Read config"
  shell: "cat /etc/replicated/tfe_settings.json | jq -c ."
  register: config_content

- name: "Load config"
  shell: "replicatedctl app-config import"
  args:
    stdin: "{{ config_content.stdout | string }}"
```

But I always end up with a `"Error: decode json: EOF"` error from replicatedctl.

What is weird is that if I replace the **replicatedctl** command with **jq** I get no json errros : 

```
- name: "Read config"
  shell: "cat /etc/replicated/tfe_settings.json | jq -c ."
  register: config_content

- name: "Load config"
  shell: jq . # this work as expected
  args:
    stdin: "{{ config_content.stdout | string }}"
```

I am using :
- ansible 2.9.2
- Replicated version 2.40.2 (git="dea3a69", date="2019-11-22 20:53:05 +0000 UTC")

If you see this and have a bit of time to check that would be awesome!

btw : I might be missing something but it personally think it is weird that there is no other option than stdin for passing config...

Anyway, thanks in advance.

Pierre.
